Fix discord rich presence length
Team-BTMC/osu-radio pull request #46
Opened 2024-10-09 05:09 UTC by hrfarmer

Right now, the rich presence would pull the length of the song from the value retrieved in osu!.db, however that length is the *drain time* and not the actual length of the mp3, so most of the time there was discrepancies. This gets around that by directly passing the duration from the player, however it's a little bit sketch because I had to put it in a setTimeout because player.duration takes some amount of time to load the data.

2024-10-09 07:08 UTC, brw commented
Might be able to do something with an eventlistener for [loadedmetadata](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/loadedmetadata_event) instead? Would not really want the timeouts tbh. I'll try some stuff tomorrow/later today or you can give it a try

2024-10-09 15:31 UTC, CaptSiro requested changes

2024-10-09 15:31 UTC, CaptSiro commented on src/renderer/src/lib/Music.ts
> +  player.onloadedmetadata = async () => {
Use `addEventListener` instead

2024-10-09 15:31 UTC, CaptSiro commented on src/renderer/src/lib/Music.ts
> +  player.onloadedmetadata = async () => {
Same as above

2024-10-09 16:17 UTC, hrfarmer commented
nvm im fairly certain i broke some other stuff with this, when i get a chance im going to look into that

2024-10-09 17:21 UTC, brw commented
You shouldn't call `addEventListener` every time an action happens. Event listeners should be registered once. Otherwise you just keep stacking event listeners on top of one another.

2024-10-10 06:41 UTC, CaptSiro commented
Thanks for pointing out @brw . I didn't realize that adding the listener happens in function. At that point do we need to add the listener? Can't we call the listener's callback directly?

2024-10-10 22:14 UTC, brw commented
@CaptSiro 
> Can't we call the listener's callback directly?
Dunno what you mean by that

> At that point do we need to add the listener?
Right after defining the audio player I guess. I assume that's fine and you can just grab the most up-to-date data to send to `discord::play`? I'm not really familiar with Solidjs and its Signals

2024-10-11 15:01 UTC, hrfarmer commented
going to remake this once the new ui is merged because the code changes a bunch, and also im pretty sure the direction i was going in was wrong anyways

2024-10-11 15:01 UTC, closed without merging